# Generated by Django 5.2.10 on 2026-01-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(help_text='Contoh: Frontend Developer', max_length=255)),
                ('deskripsi', models.TextField(help_text='Salin-tempel deskripsi pekerjaan di sini')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita'), ('Lainnya', 'Lainnya'), ('Tidak Diketahui', 'Tidak Diketahui')], default='Tidak Diketahui', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HasilAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_kecocokan', models.IntegerField()),
                ('ringkasan_evaluasi', models.TextField()),
                ('kelebihan', models.JSONField(default=list)),
                ('kekurangan', models.JSONField(default=list)),
                ('putusan_akhir', models.CharField(max_length=100)),
                ('tanggal_analisis', models.DateTimeField(auto_now_add=True)),
                ('deskripsi_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_sorter.jobdescription')),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_sorter.pelamar')),
            ],
            options={
                'ordering': ['-skor_kecocokan'],
            },
        ),
    ]
